// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcEUNyIa7hw_JM9J7Ptn9H8GD3ezfmh8',
    appId: '1:772237323603:web:a281ee94783e0ca26e05a6',
    messagingSenderId: '772237323603',
    projectId: 'extratech-6b6af',
    authDomain: 'extratech-6b6af.firebaseapp.com',
    storageBucket: 'extratech-6b6af.firebasestorage.app',
    measurementId: 'G-9L802KEYJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRrZP1IXMWPzgeWKDUhQtF6x6RF6XVK50',
    appId: '1:772237323603:android:c93b82387533f9ed6e05a6',
    messagingSenderId: '772237323603',
    projectId: 'extratech-6b6af',
    storageBucket: 'extratech-6b6af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_rsTWYxTA_bz9hGON-zlbdtxqIAiKXU',
    appId: '1:772237323603:ios:6211631bec3df05f6e05a6',
    messagingSenderId: '772237323603',
    projectId: 'extratech-6b6af',
    storageBucket: 'extratech-6b6af.firebasestorage.app',
    iosBundleId: 'com.example.ems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_rsTWYxTA_bz9hGON-zlbdtxqIAiKXU',
    appId: '1:772237323603:ios:6211631bec3df05f6e05a6',
    messagingSenderId: '772237323603',
    projectId: 'extratech-6b6af',
    storageBucket: 'extratech-6b6af.firebasestorage.app',
    iosBundleId: 'com.example.ems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApcEUNyIa7hw_JM9J7Ptn9H8GD3ezfmh8',
    appId: '1:772237323603:web:f17eeae13d60e84e6e05a6',
    messagingSenderId: '772237323603',
    projectId: 'extratech-6b6af',
    authDomain: 'extratech-6b6af.firebaseapp.com',
    storageBucket: 'extratech-6b6af.firebasestorage.app',
    measurementId: 'G-JELB556X8B',
  );
}
